function data()
    return {
       en = {
            add = "Add",
            adjust_capacity = "Adjust capacity",
            adjust_capacity_tip = "Adjustment of the calculated capacity.",
            cargo_group = "Cargo group",
            cargo_tracking = "Cargo Tracking",
            consumer = "Consumer",
            default = "Default",
            default_maximal_train_length = "Default maximal train length",
            default_maximal_train_length_tip = "The maximal train length.\nCan be overridden by line settings.",
            delete_cargo_group = "Delete cargo group",
            delete_cargo_group_member = "Delete cargo group member",
            delete_shipping_contract = "Delete shipping contract",
            disabled = "Disabled",
            disabled_for_line = "Autosizer disabled for this line",
            enable_debug = "Enable debug",
            enable_timings = "Enable timings",
            enabled = "Enabled",
            fixed_amount = "Fixed amount",
            in_use_cant_delete = "In use, can't delete",
            industry = "Industry",
            line_name = "Line name",
            lines = "Lines",
            manual = "Manual",
            minimal_train_wagon_count = "Minimal train wagon count",
            minimal_train_wagon_count_tip = "Minimal number of wagons each train should always have",
            mod_desc = "Automatically adds or removes wagons to the train to meet required cargo carrying capacities.",
            name = "Name",
            name_desc = "Train Autosizer",
            new_cargo_group = "New cargo group",
            new_shipping_contract = "New shipping contract",
            pickup_waiting = "Pick up waiting",
            pickup_wating_tip = "Additional amount of waiting cargo to pick up,\nover the calculated value.",
            rename_cargo_group = "Rename cargo group",
            rename_shipping_contract = "Rename shipping contract",
            settings = "Settings",
            shipping_contract = "Shipping contract",
            stations = "Stations",
            status_configured = "Configured",
            status_miconfigured_stations = "No stations enabled or incomplete station config",
            status_miconfigured_wagons = "Wagons with different capacities",
            supplier = "Supplier",
            train_length = "Train length",
            wagons = "Wagons",
            wagons_refresh_tip = "Rebuild the list of available wagons",
    }
}
end
 